plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
    alias(libs.plugins.kotlin.compose)
}

// قراءة ملف local.properties
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    namespace 'com.example.graduationproject'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.graduationproject"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "GEMINI_API_KEY",
                "\"${localProperties.getProperty('GEMINI_API_KEY', '')}\""

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }



    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig true
        compose true
    }
}

dependencies {

    // AndroidX
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.activity
    implementation libs.activity.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.constraintlayout
    implementation libs.cardview
    implementation libs.engage.core

    // Material
    implementation libs.material

    // RecyclerView
    implementation 'androidx.recyclerview:recyclerview:1.3.2'

    // Charts
    implementation libs.mpandroidchart

    // Flexbox
    implementation libs.flexbox

    // Animations
    implementation libs.lottie
    implementation libs.rive.android

    // Navigation
    implementation("androidx.navigation:navigation-fragment-ktx:2.8.0")
    implementation("androidx.navigation:navigation-ui-ktx:2.8.0")

    // Gemini / Network
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // Firebase
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.ai
    implementation "com.google.firebase:firebase-appcheck-debug"

    // Utilities
    implementation "com.google.guava:guava:31.0.1-android"

    // Images
    implementation libs.glide
    implementation libs.shimmer
    annotationProcessor libs.glide.compiler

    // Jetpack Compose
    implementation platform(libs.compose.bom)
    implementation libs.activity.compose
    implementation libs.material3
    implementation libs.ui
    implementation libs.ui.graphics
    implementation libs.ui.tooling.preview

    // Testing
    testImplementation libs.junit

    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ui.test.junit4

    debugImplementation libs.ui.test.manifest
    debugImplementation libs.ui.tooling
}